# http://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - ./.travis-install-kludge.sh
  - pip install 'pep8' --use-mirrors

script: nosetests test/unit
